// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.3
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Model
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.11.3")]
	public partial class Transaction : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"Transaction\",\"namespace\":\"Model\",\"fields\":[{\"name\":\"Prod" +
				"uct\",\"type\":\"string\"},{\"name\":\"Quantity\",\"type\":\"int\"},{\"name\":\"Value\",\"type\":\"d" +
				"ouble\"}]}");
		private string _Product;
		private int _Quantity;
		private double _Value;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return Transaction._SCHEMA;
			}
		}
		public string Product
		{
			get
			{
				return this._Product;
			}
			set
			{
				this._Product = value;
			}
		}
		public int Quantity
		{
			get
			{
				return this._Quantity;
			}
			set
			{
				this._Quantity = value;
			}
		}
		public double Value
		{
			get
			{
				return this._Value;
			}
			set
			{
				this._Value = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.Product;
			case 1: return this.Quantity;
			case 2: return this.Value;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.Product = (System.String)fieldValue; break;
			case 1: this.Quantity = (System.Int32)fieldValue; break;
			case 2: this.Value = (System.Double)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
